name: 'Block pr to main'

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - 'main'

jobs:
  pr-title:
    name: 'Block pr to main'
    runs-on: ubuntu-20.04
    #container: ubuntu:20.04
    steps:
      - name: 'Block pr to main'
        run: |
          printenv
          echo "Pull request to main branch is strictly prohibited!!!"
          exit 1
