name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
    # we don't need to check pr title to 'main' because merge to 'main' will
    # be done by 'merge.yml' workflow
    branches-ignore:
      - 'main'

permissions: write-all

jobs:
  pr-title:
    name: 'Title'
    #runs-on: [self-hosted, infra]
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Check current branch'
        run: |
          if [[ "${GITHUB_REF_NAME}" == "${BASE_BRANCH}" ]] ; then
            echo "Pull request to main branch is strictly prohibited"
            exit 1
          else
            echo "Branch is Ok"
          fi

      - name: 'Validate PR title'
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            chore
            ci
            docs
            feat
            fix
            refactor
            revert
            style
            test
          requireScope: false
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.
          wip: true
          validateSingleCommit: false
