name: Publish OpenAPI server docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string

permissions: write-all

env:
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  docs-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy command
        run: |
          echo ---
          echo ${RELEASE_VERSION}
