name: Publish OpenAPI server docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  docs-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy command
        run: |
          echo ---
          echo ${{ inputs.version }}
