name: Publish OpenAPI server docs

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  docs-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Dummy command
        run: |
          echo "It works"
